language: python
python:
  - "2.7"
branches:
  only:
    - source
install: "pip install -r requirements.txt"
script:
  - make publish github
env:
  global:
    - secure: SjdFJEagIwjFWdR3e3OiUT8ff4l8MsQLceXCsR8G/h3Xdi2M3pJNl67k9VxuMds5u4kszgVb84NE6hpX9+HV1XlqJZkIgw3tWLGgyurmjpHCddeQ4g/MPuftDEbphr45E9cQXIY3Ip4F0087YxDFkVMfWgwClDnzU5kCOpkmP976miam+8uKG+b/Y8jtDnez1LPHU+4iI815zzv+sLKwhmUdXHS34ejS0Qgdvi4slO2xpQGom9sejJvv/vx45hWHryjCYIZ0OIFA2Yyrh4HY/GnDrKJHoTsjkjePGinADDa2LpKnxvav55u14eKIuV2FghPkTkFlk9b/iZIGqWTOUJD23fqZMFZmHQmQcbLB50riDCPxwyL9Y3bClCI/ngDeLmHhHs9f6KTd0ut62muPwEu7hb/ANYwVsKR5UyAyEqlXMGusiInzgK9F1KzbAiySsFpvq8gZ2QGZ+0NKvxiGiHkWEf6DtOD1gvrQFVY23Ww0VORskyc1mu41E88lpoKquYx3I2bUWvcBhcztsPubVw9tVmRbgU2V2MoVOpZFcDLDyekG5eaW+VnVUJDjS6N7OGC2LpIx8PzKW4A7jXDIpehLVWf2vG14MPicahgpHzUBXDVc/1VvVY0NWmnLkTE4ZTC4f7DZhA96/gOUP0jVh9ejR/04VUCmKmd1I6zOiPw=